# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Push Nun singet und seid froh Docker images

on:
  release:
    types: [published]
  push:
    branches: [ "master" ]
    tags:
      - v*.*.*

env:
  REGISTRY: ghcr.io

jobs:
  docker-garamond:
    name: Push Garamond Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images:  ${{ env.REGISTRY }}/nun-singet-und-seid-froh/garamond
          tags: ${{ env.GITHUB_REF_TYPE == 'tag' && env.GITHUB_REF_NAME || 'latest' }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.9.0
        with:
          context: .
          push: true
          file: Dockerfile.garamond
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  docker-lilypond:
    name: Push Lilypond Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: docker-garamond
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images:  ${{ env.REGISTRY }}/nun-singet-und-seid-froh/lilypond
          tags: ${{ env.GITHUB_REF_TYPE == 'tag' && env.GITHUB_REF_NAME || 'latest' }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.9.0
        with:
          context: .
          push: true
          file: Dockerfile.lilypond
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  docker-xelatex:
    name: Push Xelatex Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: docker-garamond
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images:  ${{ env.REGISTRY }}/nun-singet-und-seid-froh/xelatex
          tags: ${{ env.GITHUB_REF_TYPE == 'tag' && env.GITHUB_REF_NAME || 'latest' }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.9.0
        with:
          context: .
          push: true
          file: Dockerfile.xelatex
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
